-- Tabela para comentários
CREATE TABLE IF NOT EXISTS trello_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id BIGINT REFERENCES trello_cards(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela para anexos
CREATE TABLE IF NOT EXISTS trello_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id BIGINT REFERENCES trello_cards(id) ON DELETE CASCADE,
    file_name TEXT NOT NULL,
    file_url TEXT NOT NULL,
    file_type TEXT,
    file_size INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela para etiquetas
CREATE TABLE IF NOT EXISTS trello_labels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    color TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela de relacionamento entre cards e etiquetas
CREATE TABLE IF NOT EXISTS trello_card_labels (
    card_id BIGINT REFERENCES trello_cards(id) ON DELETE CASCADE,
    label_id BIGINT REFERENCES trello_labels(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (card_id, label_id)
);

-- Criar índices para melhor performance
CREATE INDEX IF NOT EXISTS idx_comments_card_id ON trello_comments(card_id);
CREATE INDEX IF NOT EXISTS idx_attachments_card_id ON trello_attachments(card_id);
CREATE INDEX IF NOT EXISTS idx_card_labels_card_id ON trello_card_labels(card_id);
CREATE INDEX IF NOT EXISTS idx_card_labels_label_id ON trello_card_labels(label_id);

-- Desabilitar RLS para essas tabelas
ALTER TABLE trello_comments DISABLE ROW LEVEL SECURITY;
ALTER TABLE trello_attachments DISABLE ROW LEVEL SECURITY;
ALTER TABLE trello_labels DISABLE ROW LEVEL SECURITY;
ALTER TABLE trello_card_labels DISABLE ROW LEVEL SECURITY;

-- Criar trigger para atualizar o updated_at
CREATE TRIGGER update_trello_comments_updated_at
    BEFORE UPDATE ON trello_comments
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_trello_attachments_updated_at
    BEFORE UPDATE ON trello_attachments
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Inserir etiquetas padrão
INSERT INTO trello_labels (title, color)
VALUES 
    ('Urgente', '#EF4444'),
    ('Importante', '#F59E0B'),
    ('Normal', '#10B981'),
    ('Baixa Prioridade', '#6B7280'),
    ('Bloqueado', '#7C3AED')
ON CONFLICT DO NOTHING; 