-- Criar tabela de checklists
CREATE TABLE IF NOT EXISTS trello_checklists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id BIGINT REFERENCES trello_cards(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    position INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Criar tabela de itens do checklist
CREATE TABLE IF NOT EXISTS trello_checklist_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checklist_id BIGINT REFERENCES trello_checklists(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    checked BOOLEAN DEFAULT FALSE,
    position INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Criar tabela de comentários
CREATE TABLE IF NOT EXISTS trello_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id BIGINT REFERENCES trello_cards(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Criar tabela de anexos
CREATE TABLE IF NOT EXISTS trello_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id BIGINT REFERENCES trello_cards(id) ON DELETE CASCADE,
    file_name TEXT NOT NULL,
    file_url TEXT NOT NULL,
    file_type TEXT,
    file_size INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Criar tabela de etiquetas
CREATE TABLE IF NOT EXISTS trello_labels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    color VARCHAR(7) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Criar tabela de relacionamento entre cards e etiquetas
CREATE TABLE IF NOT EXISTS trello_card_labels (
    card_id BIGINT REFERENCES trello_cards(id) ON DELETE CASCADE,
    label_id BIGINT REFERENCES trello_labels(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (card_id, label_id)
);

-- Criar índices para melhor performance
CREATE INDEX IF NOT EXISTS idx_trello_checklists_card_id ON trello_checklists(card_id);
CREATE INDEX IF NOT EXISTS idx_trello_checklist_items_checklist_id ON trello_checklist_items(checklist_id);
CREATE INDEX IF NOT EXISTS idx_trello_comments_card_id ON trello_comments(card_id);
CREATE INDEX IF NOT EXISTS idx_trello_attachments_card_id ON trello_attachments(card_id);
CREATE INDEX IF NOT EXISTS idx_trello_card_labels_card_id ON trello_card_labels(card_id);
CREATE INDEX IF NOT EXISTS idx_trello_card_labels_label_id ON trello_card_labels(label_id);

-- Desabilitar RLS para essas tabelas
ALTER TABLE trello_checklists DISABLE ROW LEVEL SECURITY;
ALTER TABLE trello_checklist_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE trello_comments DISABLE ROW LEVEL SECURITY;
ALTER TABLE trello_attachments DISABLE ROW LEVEL SECURITY;
ALTER TABLE trello_labels DISABLE ROW LEVEL SECURITY;
ALTER TABLE trello_card_labels DISABLE ROW LEVEL SECURITY;

-- Remover triggers se existirem
DROP TRIGGER IF EXISTS update_trello_checklists_updated_at ON trello_checklists;
DROP TRIGGER IF EXISTS update_trello_checklist_items_updated_at ON trello_checklist_items;
DROP TRIGGER IF EXISTS update_trello_comments_updated_at ON trello_comments;
DROP TRIGGER IF EXISTS update_trello_attachments_updated_at ON trello_attachments;

-- Criar triggers
CREATE TRIGGER update_trello_checklists_updated_at
    BEFORE UPDATE ON trello_checklists
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_trello_checklist_items_updated_at
    BEFORE UPDATE ON trello_checklist_items
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_trello_comments_updated_at
    BEFORE UPDATE ON trello_comments
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_trello_attachments_updated_at
    BEFORE UPDATE ON trello_attachments
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Inserir etiquetas padrão
INSERT INTO trello_labels (title, color)
VALUES 
    ('Urgente', '#EF4444'),
    ('Importante', '#F59E0B'),
    ('Normal', '#10B981'),
    ('Baixa Prioridade', '#6B7280'),
    ('Bloqueado', '#7C3AED')
ON CONFLICT DO NOTHING; 